"""Added group_id=fk

Revision ID: 044fc52b26df
Revises: 
Create Date: 2022-04-01 01:12:43.487438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044fc52b26df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
