"""fixed

Revision ID: 4d9026754996
Revises: 044fc52b26df
Create Date: 2022-04-07 22:05:01.791986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9026754996'
down_revision = '044fc52b26df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
