"""fixed2

Revision ID: 9753d34e2d6d
Revises: 4d9026754996
Create Date: 2022-04-07 22:10:22.147485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9753d34e2d6d'
down_revision = '4d9026754996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admin") as batch_op:
        batch_op.alter_column('fullname',
                nullable=True)
        batch_op.alter_column('phone',
                nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
